### ISSUE TITLE
Create samples to demo how to use this extension

### ISSUE THREAD

**Issue by stliu** [Azure/azure-jdbc-msi-extension#3]
We should create a sample ( or samples ) to demo how to use this extension in a **pure** JDBC environment.

Ideally, the samples should cover:

## Hosting Environment

* App Services
* Azure Spring Cloud

## Database

* Azure PostgreSQL Single Server
* Azure MySQL Single Server

And the sample should cover the E2E scenario of :

1. Create a hosting environment (App Service / Azure Spring Cloud)
2. Create Managed Identity (System Assigned / User Assigned, if applicable )
3. Create Database (MySQL / PostgreSQL ) and enable AAD integration
4. [Creating a MySQL user for your Managed Identity]https://docs.microsoft.com/en-us/azure/mysql/howto-connect-with-managed-identity#creating-a-mysql-user-for-your-managed-identity
5. Deploy sample to the hosting environment using Managed Identity to connect to Database

It would be nice to have terraform script provided in the sample, so everyone can run the sample easily

**Comment by stliu** [comment]
@felipmiguel  I just created this issue and assigned it to you, thanks and let me know your thoughts

**Comment by stliu** [comment]
The extension code will not hard depend on any jdbc driver, but I'm using **provided** scope, see [here](https://github.com/Azure/azure-jdbc-msi-extension/blob/main/jdbc/pom.xml#L21)

So, I'm thinking probably we can use maven profile in the sample project, to bringing each JDBC driver.

something like

```xml

<profiles>

    <profile>
        <id>mysql-5</id>
        <dependencies>
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>5.1.49</version>
            </dependency>
        </dependencies>
    </profile>
    <profile>
        <id>mysql-8</id>
        <dependencies>
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>8.0.28</version>
            </dependency>
        </dependencies>
    </profile>
</profiles>
```

Then maybe we can reuse this sample in our interaction tests as mentioned in #4

**Comment by felipmiguel** [comment]
@stliu   As this application will be hosted in an App Service or Azure Spring Cloud I'll create a simple Rest API that performs a query on a database. Does it make sense?

**Comment by saragluna** [comment]
Samples created in https://github.com/Azure-Samples/Passwordless-Connections-for-Java-Apps, closing this issue now.
