### ISSUE TITLE
Setup integration test to cover common scenarios

### ISSUE THREAD

**Issue by stliu** [Azure/azure-jdbc-msi-extension#4]
### Context
Once we have the terraform scripts to provision the hosting environment ( app service / azure spring cloud ) and databases ( MySQL / PostgreSQL) in #3, we should start to set up the integration test CI pipeline using **Github Actions**

### Goal
In the CI pipeline, I'd expect to test the following scenarios matrix:

`{hosting environment} * [system assigned identity | user assigned identity] * {Database} * {Database JDBC Driver supported versions}`

**Hosting Environment：** 
1. App Service    2. Azure Spring Cloud

**Identity type：** 
1. System Assigned     2. User Assigned

**Databases：** 
1. Mysql    2. Postgresql

**JDBC Driver Version：** 
1. MySQL   （ [8.0.28](https://search.maven.org/artifact/mysql/mysql-connector-java/8.0.28/jar) / [5.1.49](https://search.maven.org/artifact/mysql/mysql-connector-java/5.1.49/jar)）   2. PostgreSQL （ [42.3.3](https://search.maven.org/artifact/org.postgresql/postgresql/42.3.3/jar)）

**Comment by saragluna** [comment]
Close in favor of https://github.com/Azure/azure-sdk-for-java/issues/30762 and https://github.com/Azure/azure-sdk-for-java/issues/30763.
