### ISSUE TITLE
set up github bot to add issues / pr into github project

### ISSUE THREAD

**Issue by stliu** [Azure/azure-jdbc-msi-extension#5]
Inspired by this https://github.com/microsoftgraph/msgraph-sdk-java-core/commit/9553a0d663fc324226ef55ad8cbd4402dd434122

We use this project to track progress https://github.com/orgs/Azure/projects/94/views/1

it would be nice to have every issue / PR automatically add to the project

**Comment by backwind1233** [comment]
Closing this issue, duplicated with this [issue](https://github.com/Azure/azure-sdk-for-java/issues/28019).
